name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.13"

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Stop PM2
        run: pm2 stop server
        if: ${{failure()}}

      - name: Start PM2
        run: pm2 start "npm run start" --name server
